# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Home(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(250, 30, 301, 91))
        self.label.setStyleSheet("font: 1000 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Widget)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 310, 261, 81))
        self.pushButton_2.setMinimumSize(QtCore.QSize(261, 0))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Widget)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 180, 261, 81))
        self.pushButton_3.setMinimumSize(QtCore.QSize(261, 0))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "<html><head/><body><p align=\"center\">Добро пожаловать в</p><p align=\"center\">  систему</p></body></html>"))
        self.pushButton_2.setText(_translate("Widget", "Регистрация нового сотрудника"))
        self.pushButton_3.setText(_translate("Widget", "Авторизация"))

